#  Copyright (c) 2005-2007 Andre Merzky (andre@merzky.net)
#  Copyright (c) 2010 Ole Weidner (oweidner@cct.lsu.edu)
#
#  Use, modification and distribution is subject to the Boost Software
#  License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt)

-include make.cfg
-include $(SAGA_MAKE_INCLUDE_ROOT)/saga.mk

default::
	@$(TRUE)

distclean::
	@$(RM) make.cfg saga.config.*.mk

