#
#   Copyright (c) 2008 João Abecasis
#
#   Distributed under the Boost Software License, Version 1.0. (See accompanying
#   file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

SAGA_ROOT               = ../../../../

SAGA_TEST_RUN           = ./run_adaptor_tests.sh.run

SAGA_DONT_INSTALL       = yes

include $(SAGA_ROOT)/make/saga.test.mk

