#  Copyright (c) 2005-2006 Andre Merzky (andre@merzky.net)
#  Copyright (c) 2006-2007 Ole Weidner (oweidner@cct.lsu.edu)
# 
#  Use, modification and distribution is subject to the Boost Software
#  License, Version 1.0. (See accompanying file LICENSE_1_0.txt 
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

SAGA_OBJ      += saga_gass_server.o
SAGA_OBJC     += globus_gram_job_adaptor_gass_server_ez.o

SAGA_CONFDIR      = ../../config
SAGA_REQUIREMENTS = globus globus_gass_copy

-include ../../config/make.cfg
-include $(SAGA_MAKE_INCLUDE_ROOT)/saga.mk 

