/* gridsamJobControlSOAPBindingProxy.cpp
   Generated by gSOAP 2.7.11 from ./wsdl/wsdl/gridsam.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "gridsamJobControlSOAPBindingProxy.h"

JobControlSOAPBindingProxy::JobControlSOAPBindingProxy()
{	JobControlSOAPBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

JobControlSOAPBindingProxy::JobControlSOAPBindingProxy(const struct soap &soap)
{	soap_copy_context(this, &soap);
	JobControlSOAPBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

JobControlSOAPBindingProxy::JobControlSOAPBindingProxy(soap_mode iomode)
{	JobControlSOAPBindingProxy_init(iomode, iomode);
}

JobControlSOAPBindingProxy::JobControlSOAPBindingProxy(soap_mode imode, soap_mode omode)
{	JobControlSOAPBindingProxy_init(imode, omode);
}

void JobControlSOAPBindingProxy::JobControlSOAPBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"myproxy", "urn:gridsam:myproxy", NULL, NULL},
	{"jsdl", "http://schemas.ggf.org/jsdl/2005/11/jsdl", NULL, NULL},
	{"jsdlposix", "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix", NULL, NULL},
	{"gridsam2", "http://schemas.ggf.org/jsdl/2006/07/jsdl-hpcp", NULL, NULL},
	{"mpi", "urn:gridsam:mpi", NULL, NULL},
	{"jobcontrol", "http://www.icenigrid.org/service/gridsam/JobControlSOAPBinding", NULL, NULL},
	{"jobmonitoring", "http://www.icenigrid.org/service/gridsam/JobMonitoringSOAPBinding", NULL, NULL},
	{"jobsubmission", "http://www.icenigrid.org/service/gridsam/JobSubmissionSOAPBinding", NULL, NULL},
	{"gridsam", "http://www.icenigrid.org/service/gridsam", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	if (!this->namespaces)
		this->namespaces = namespaces;
}

JobControlSOAPBindingProxy::~JobControlSOAPBindingProxy()
{ }

void JobControlSOAPBindingProxy::soap_noheader()
{	header = NULL;
}

const SOAP_ENV__Fault *JobControlSOAPBindingProxy::soap_fault()
{	return this->fault;
}

const char *JobControlSOAPBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *JobControlSOAPBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int JobControlSOAPBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

void JobControlSOAPBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void JobControlSOAPBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *JobControlSOAPBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int JobControlSOAPBindingProxy::terminateJob(_gridsam__terminateJob *gridsam__terminateJob, _gridsam__terminateJobResponse *gridsam__terminateJobResponse)
{	struct soap *soap = this;
	struct __jobcontrol__terminateJob soap_tmp___jobcontrol__terminateJob;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/gridsam";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___jobcontrol__terminateJob.gridsam__terminateJob = gridsam__terminateJob;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___jobcontrol__terminateJob(soap, &soap_tmp___jobcontrol__terminateJob);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___jobcontrol__terminateJob(soap, &soap_tmp___jobcontrol__terminateJob, "-jobcontrol:terminateJob", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___jobcontrol__terminateJob(soap, &soap_tmp___jobcontrol__terminateJob, "-jobcontrol:terminateJob", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!gridsam__terminateJobResponse)
		return soap_closesock(soap);
	gridsam__terminateJobResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	gridsam__terminateJobResponse->soap_get(soap, "gridsam:terminateJobResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int JobControlSOAPBindingProxy::startJob(_gridsam__startJob *gridsam__startJob, _gridsam__startJobResponse *gridsam__startJobResponse)
{	struct soap *soap = this;
	struct __jobcontrol__startJob soap_tmp___jobcontrol__startJob;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/gridsam";
	soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___jobcontrol__startJob.gridsam__startJob = gridsam__startJob;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___jobcontrol__startJob(soap, &soap_tmp___jobcontrol__startJob);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___jobcontrol__startJob(soap, &soap_tmp___jobcontrol__startJob, "-jobcontrol:startJob", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___jobcontrol__startJob(soap, &soap_tmp___jobcontrol__startJob, "-jobcontrol:startJob", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!gridsam__startJobResponse)
		return soap_closesock(soap);
	gridsam__startJobResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	gridsam__startJobResponse->soap_get(soap, "gridsam:startJobResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
